services:

  transaction-api:
    build:
      context: ./services/transaction-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/finguard
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AWS_PROFILE: finguard-dev
      AWS_DEFAULT_REGION: ca-central-1
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
    depends_on:
      postgres:
        condition: service_healthy

  risk-worker:
    build:
      context: ./services/risk-worker
    environment:
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AWS_PROFILE: finguard-dev
      AWS_DEFAULT_REGION: ca-central-1
    volumes:
      - ${HOME}/.aws:/root/.aws:ro

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finguard
      POSTGRES_USER: finguard
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finguard -d finguard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: