spring.application.name=transaction-api

spring.datasource.url=jdbc:postgresql://localhost:5432/finguard
spring.datasource.username=finguard
spring.datasource.password=1112mike

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true