spring.application.name=transaction-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finguard}
spring.datasource.username=${DB_USERNAME:finguard}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

finguard.sqs.transaction-queue-url=${SQS_QUEUE_URL}